[package]
name = "register_transfer_names_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
register_transfer_names_api = { path = "../api" }